services:
  alertstream-door-b:
    extends:
      file: ../docker-compose.yml
      service: app

    container_name: pkp_securegate_alertstream_door_b

    image: pkp-securegate:033fb33c917567f2c9abdde27a1e8396b4122668

    entrypoint:
      - php

    command:
      - artisan
      - door:stream-events
      - DOOR-B

    ports: !reset []

    healthcheck:
      disable: true

    restart: unless-stopped
